#base "scheme/colors_default.res"
#base "scheme/colors_classic.res"
#base "scheme/borders_default.res"
#base "scheme/borders_classic.res"
#base "scheme/fonts_default.res"
#base "scheme/fonts_classic.res"
#base "scheme/basesettings.res"