#base "../../cfg/hl_ar_charinfoloadoutsubpanel.txt"
#base "../customizations/aspect_ratio/16x9/charinfoloadoutsubpanel.res"

"Resource/UI/CharInfoLoadoutSubPanel.res"
{
	"CharInfoLoadoutSubPanel"
	{
		"ControlName"	"Frame"
		"fieldName"		"CharInfoLoadoutSubPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"proportionaltoparent"	"1"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"0"
		"bgcolor_override"	"46 43 42 0"
		"infocus_bgcolor_override" "46 43 42 0"
		"outoffocus_bgcolor_override" "46 43 42 0"
		
		"selectlabely_default"		"25"
		"selectlabely_onchanges"	"15"
		
		"class_ypos"				"40"
		"class_xdelta"				"5"
		"class_wide_min"			"60"
		"class_wide_max"			"100"
		"class_tall_min"			"120"
		"class_tall_max"			"200"
		"class_distance_min"		"7"
		"class_distance_max"		"100"

		"itemcountcolor"			"200 80 60 255"
		"itemcountcolor_noitems"	"117 107 94 255"
	}
	
	"Background"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"Background"
		"ypos"			"0"
		"zpos"			"-2"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"border"		"c_src_convex"
		"bgcolor_override"		"c_src_bgcolor"
	}
	
	"C_MenuWarPaints"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuWarPaints"
		"xpos"			"12"
		"ypos"			"r122"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"paintkit_preview"
		"labeltext"		"War Paints"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"0"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
	}
	
	"C_MenuTrading"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuTrading"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"trading"
		"labeltext"		"Trading"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuWarPaints"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuCrafting"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuCrafting"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"crafting"
		"labeltext"		"Crafting"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuTrading"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuBackpack"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuBackpack"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"backpack"
		"labeltext"		"Inventory"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuCrafting"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuSpacer"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"C_MenuSpacer"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		
		"pin_to_sibling"		"C_MenuBackpack"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuSpy"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuSpy"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout spy"
		"labeltext"		"Spy"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuSpacer"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuSniper"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuSniper"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout sniper"
		"labeltext"		"Sniper"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuSpy"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuMedic"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuMedic"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout medic"
		"labeltext"		"Medic"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
			"paintborder"	"0"
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuSniper"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuEngineer"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuEngineer"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout engineer"
		"labeltext"		"Engineer"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuMedic"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuHeavy"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuHeavy"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout heavy"
		"labeltext"		"Heavy Weapons"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuEngineer"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuDemo"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuDemo"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout demoman"
		"labeltext"		"Demoman"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuHeavy"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuPyro"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuPyro"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout pyro"
		"labeltext"		"Pyro"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuDemo"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuSoldier"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuSoldier"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout soldier"
		"labeltext"		"Soldier"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"	
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuPyro"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_MenuScout"
	{
		"ControlName"	"CExButton"
		"fieldName"		"C_MenuScout"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"70"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"font"			"C_Tahoma8"
		"textAlignment"	"west"
		"command"		"loadout scout"
		"labeltext"		"Scout"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"	"UI/buttonrollover.wav"
		"proportionaltoparent"	"1"
		"paintborder"	"0"
		"paintbackground"	"0"
		"defaultfgcolor_override"	"C_MenuButtonDefault"
		"armedfgcolor_override"		"C_MenuButtonArmed"	
		
		"pin_to_sibling"		"C_MenuSoldier"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"2"
	}
	
	"C_Contents"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"C_Contents"
		"xpos"				"-14"
		"ypos"				"-8"
		"zpos"				"0"
		"visible"			"1"
		"enabled"			"1"
		
		
		"pin_to_sibling"		"Background"
		"pin_to_sibling_corner"	"0"
		"pin_corner_to_sibling"	"0"
	
		"C_Row1"
		{
			"ControlName"		"EditablePanel"
			"fieldName"			"C_Row1"
			"xpos"				"0"
			"ypos"				"0"
			"zpos"				"1"
			"wide"				"f0"
			"tall"				"p0.334"
			"visible"			"1"
			"enabled"			"1"
			"proportionaltoparent"	"1"
			
			"Scout"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Scout"
				"xpos"				"0"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Scout"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-1"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"The youngest of eight boys from the south side of Boston, the Scout learned early how to problem solve with his fists. With seven older brothers on his side, fights tended to end before the runt of the litter could maneuver into punching distance, so the Scout trained himself to run. He ran everywhere, all the time, until he could beat his pack of mad dog siblings to the fray."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout scout"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Soldier"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Soldier"
				"xpos"				"cs-0.5"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Soldier"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-2"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"Though he wanted desperately to fight in World War 2, the Soldier was rejected from every branch of the U.S. military. Undaunted, he bought his own ticket to Europe. After arriving and finally locating Poland, the Soldier taught himself how to load and fire a variety of weapons before embarking on a Nazi killing spree for which he was awarded several medals that he designed and made himself. His rampage ended immediately upon hearing about the end of the war in 1949."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout soldier"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Pyro"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Pyro"
				"xpos"				"rs1"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Pyro"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-3"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"Only two things are known for sure about the mysterious Pyro: he sets things on fire and he doesn't speak. In fact, only the part about setting things on fire is undisputed. Some believe his occasional rasping wheeze may be an attempt to communicate through a mouth obstructed by a filter and attached to lungs ravaged by constant exposure to his asbestos-lined suit. Either way, he's a fearsome, inscrutable, on-fire Frankenstein of a man - if he even is a man."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout pyro"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Bottom"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Bottom"
				"xpos"				"0"
				"ypos"				"rs1"
				"zpos"				"1"
				"wide"				"f0"
				"tall"				"1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				"border"	"c_src_concave"
			}
		}
		
		"C_Row2"
		{
			"ControlName"		"EditablePanel"
			"fieldName"			"C_Row2"
			"xpos"				"0"
			"ypos"				"0"
			"zpos"				"1"
			"wide"				"f0"
			"tall"				"p0.334"
			"visible"			"1"
			"enabled"			"1"
			"proportionaltoparent"	"1"
			
			"pin_to_sibling"		"C_Row1"
			"pin_to_sibling_corner"	"2"
			"pin_corner_to_sibling"	"0"
			
			"Demo"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Demo"
				"xpos"				"0"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Demoman"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-4"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"A fierce temper, a fascination with all things explosive, and a terrible plan to kill the Loch Ness Monster cost the six year old Demoman his original set of adoptive parents. Later, back at the Crypt Grammar School for Orphans near Ullapool in the Scottish Highlands, the boy's bomb-making skills improved dramatically. His disposition and total number of intact eyeballs, however, did not."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout demoman"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Heavy"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Heavy"
				"xpos"				"cs-0.5"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Heavy Weapons Guy"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-5"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"Like a hibernating bear, the Heavy appears to be a gentle giant. Also like a bear, confusing his deliberate, sleepy demeanor with gentleness will get you ripped limb from limb. Though he speaks simply and moves with an economy of energy that's often confused with napping, the Heavy isn't dumb, he's not your big friend, and he generally wishes you'd just shut up before he has to make you shut up."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout heavy"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Engineer"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Engineer"
				"xpos"				"rs1"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Engineer"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-6"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"This amiable, soft-spoken good ol' boy from tiny Bee Cave, Texas loves barbeque, guns, and higher education. Natural curiosity, ten years as a roughneck in the west Texas oilfields, and eleven hard science PhDs have trained him to design, build and repair a variety of deadly contraptions."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout engineer"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Bottom"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Bottom"
				"xpos"				"0"
				"ypos"				"rs1"
				"zpos"				"1"
				"wide"				"f0"
				"tall"				"1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				"border"	"c_src_concave"
			}
		}
		
		"C_Row3"
		{
			"ControlName"		"EditablePanel"
			"fieldName"			"C_Row3"
			"xpos"				"0"
			"ypos"				"0"
			"zpos"				"1"
			"wide"				"f0"
			"tall"				"p0.332"
			"visible"			"1"
			"enabled"			"1"
			"proportionaltoparent"	"1"
			
			"pin_to_sibling"		"C_Row2"
			"pin_to_sibling_corner"	"2"
			"pin_corner_to_sibling"	"0"
			
			"Medic"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Medic"
				"xpos"				"0"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Medic"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-7"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"What he lacks in compassion for the sick, respect for human dignity, and any sort of verifiable formal training in medicine, the Medic more than makes up for with a bottomless supply of giant needles and a trembling enthusiasm for plunging them into exposed flesh. Raised in Stuttgart, Germany during an era when the Hippocratic oath had been downgraded to an optional Hippocratic suggestion, the Medic considers healing a generally unintended side effect of satisfying his own morbid curiosity."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout medic"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Sniper"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Sniper"
				"xpos"				"cs-0.5"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Sniper"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-8"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"In his former life as a tracker of dangerous game in the unforgiving Australian outback, the Sniper would spend months by himself. Prolonged isolation taught him a valuable lesson: You don't have to rely on other people if you never miss."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout sniper"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
			
			"Spy"
			{
				"ControlName"		"EditablePanel"
				"fieldName"			"Spy"
				"xpos"				"rs1"
				"ypos"				"0"
				"zpos"				"1"
				"wide"				"p0.334"
				"tall"				"f1"
				"visible"			"1"
				"enabled"			"1"
				"proportionaltoparent"	"1"
				
				"Title"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Title"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"1"
					"wide"				"f0"
					"tall"				"14"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"labeltext"			"Spy"
					"fgcolor_override"			"c_src_textcolor"
					"font"			"c_src_tahoma8"
				}
				
				"Info1"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info1"
					"xpos"				"0"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.3"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info2"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info2"
					"xpos"				"p0.3"
					"ypos"				"14"
					"zpos"				"1"
					"wide"				"p0.7"
					"tall"				"28"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"#Info-9"
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Info3"
				{
					"ControlName"		"CExLabel"
					"fieldName"			"Info3"
					"xpos"				"0"
					"ypos"				"rs1"
					"zpos"				"1"
					"wide"				"f10"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"textalignment"	"north-west"
					"wrap"			"1"
					"labeltext"			"He is a puzzle, wrapped in an enigma, shrouded in riddles, lovingly sprinkled with intrigue, express mailed to Mystery, Alaska, and LOOK OUT BEHIND YOU! but it is too late. You're dead. For he is the Spy - globetrotting rogue, lady killer (metaphorically) and mankiller (for real)."
					"fgcolor_override"			"c_src_dulltextcolor"
					"font"			"c_src_tahoma7"
				}
				
				"Button"
				{
					"ControlName"		"Button"
					"fieldName"			"Button"
					"xpos"				"0"
					"ypos"				"0"
					"zpos"				"2"
					"wide"				"f0"
					"tall"				"f0"
					"visible"			"1"
					"enabled"			"1"
					"proportionaltoparent"	"1"
					"command"			"loadout spy"
					"actionsignallevel"	"4"
					
					"labeltext"			""
					"paintborder"		"0"
					"paintbackground"	"0"
				}
			}
		}
	}
	
	"Scout_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Scout_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&1"
		"Command"		"loadout scout"
	}
	
	"Soldier_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Soldier_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&2"
		"Command"		"loadout soldier"
	}
	
	"Pyro_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Pyro_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&3"
		"Command"		"loadout pyro"
	}
	
	"Demo_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Demo_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&4"
		"Command"		"loadout demoman"
	}
	
	"Heavy_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Heavy_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&5"
		"Command"		"loadout heavy"
	}
	
	"Engineer_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Engineer_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&6"
		"Command"		"loadout engineer"
	}
	
	"Medic_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Medic_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&7"
		"Command"		"loadout medic"
	}
	
	"Sniper_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Sniper_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&8"
		"Command"		"loadout sniper"
	}
	
	"Spy_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Spy_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&9"
		"Command"		"loadout spy"
	}
	
	"Inv_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Inv_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&I"
		"Command"		"backpack"
	}
	
	"Craft_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Craft_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&C"
		"Command"		"crafting"
	}
	
	"Trade_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Trade_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&T"
		"Command"		"trading"
	}
	
	"Skin_KeyBind"
	{
		"ControlName"	"CExButton"
		"fieldName"		"Skin_KeyBind"
		"xpos"			"r0"
		"ypos"			"r0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"&W"
		"Command"		"paintkit_preview"
	}
	
	"scout"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"scout"
		"xpos"				"c-300"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout scout"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_scout_red"
		"inactiveimage"		"class_sel_sm_scout_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"soldier"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"soldier"
		"xpos"				"c-250"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout soldier"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_soldier_red"
		"inactiveimage"		"class_sel_sm_soldier_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"pyro"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"pyro"
		"xpos"				"c-200"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout pyro"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_pyro_red"
		"inactiveimage"		"class_sel_sm_pyro_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"demoman"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"demoman"
		"xpos"				"c-110"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout demoman"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_demo_red"
		"inactiveimage"		"class_sel_sm_demo_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	"heavyweapons"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"heavyweapons"
		"xpos"				"c-60"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout heavy"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_heavy_red"
		"inactiveimage"		"class_sel_sm_heavy_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"engineer"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"engineer"
		"xpos"				"c-10"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout engineer"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_engineer_red"
		"inactiveimage"		"class_sel_sm_engineer_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"medic"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"medic"
		"xpos"				"c78"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout medic"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_medic_red"
		"inactiveimage"		"class_sel_sm_medic_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"sniper"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"sniper"
		"xpos"				"c128"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout sniper"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_sniper_red"
		"inactiveimage"		"class_sel_sm_sniper_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"spy"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"spy"
		"xpos"				"c178"
		"ypos"				"120"
		"zpos"				"6"
		"wide"				"60"
		"tall"				"120"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"loadout spy"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"class_sel_sm_spy_red"
		"inactiveimage"		"class_sel_sm_spy_inactive"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	
	"ShowBackpackButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowBackpackButton"
		"xpos"				"r0"
		"ypos"				"235"
		"zpos"				"6"
		"wide"				"0"
		"tall"				"60"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"backpack"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"..\hud\backpack_01"
		"inactiveimage"		"..\hud\backpack_01_grey"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	"ShowBackpackLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowBackpackLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#BackpackTitle"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"7"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"

		"pin_to_sibling"               "ShowBackpackButton"
		"pin_corner_to_sibling"        "4"          
		"pin_to_sibling_corner"        "6"  
	}
	"ShowCraftingButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowCraftingButton"
		"xpos"				"r0"
		"ypos"				"235"
		"zpos"				"6"
		"wide"				"0"
		"tall"				"60"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"crafting"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"crafting_anvil"
		"inactiveimage"		"crafting_anvil_gray"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"ShowCraftingLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowCraftingLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#CraftingExplanation_Title"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"7"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"

		"pin_to_sibling"               "ShowCraftingButton"
		"pin_corner_to_sibling"        "4"          
		"pin_to_sibling_corner"        "6"  
	}	
	"ShowArmoryButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowArmoryButton"
		"xpos"				"r0"
		"ypos"				"235"
		"zpos"				"6"
		"wide"				"0"
		"tall"				"60"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"armory"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"catalog_book"
		"inactiveimage"		"catalog_book_gray"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	"ShowArmoryLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowArmoryLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#Armory"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"7"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"

		"pin_to_sibling"               "ShowArmoryButton"
		"pin_corner_to_sibling"        "4"          
		"pin_to_sibling_corner"        "6" 
	}
	"ShowTradeButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowTradeButton"
		"xpos"				"r0"
		"ypos"				"235"
		"zpos"				"6"
		"wide"				"0"
		"tall"				"60"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"trading"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"trading_parcel"
		"inactiveimage"		"trading_parcel_gray"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	"ShowTradeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowTradeLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#TradingExplanation_Title"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"7"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"

		"pin_to_sibling"               "ShowTradeButton"
		"pin_corner_to_sibling"        "4"          
		"pin_to_sibling_corner"        "6" 
	}
	"ShowPaintkitsButton"
	{
		"ControlName"		"ImageButton"
		"fieldName"			"ShowPaintkitsButton"
		"xpos"				"r0"
		"ypos"				"235"
		"zpos"				"6"
		"wide"				"0"
		"tall"				"60"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"paintkit_preview"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleImage"		"1"
		"activeimage"		"paintkit_tool"
		"inactiveimage"		"paintkit_tool_bw"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}	
	"ShowPaintkitsLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ShowPaintkitsLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#PaintkitTitle"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"5"
		"zpos"			"7"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"

		"pin_to_sibling"               "ShowPaintkitsButton"
		"pin_corner_to_sibling"        "4"          
		"pin_to_sibling_corner"        "6" 
	}
	
	"ClassLabel"
	{
		"ControlName"	"Label"
		"fieldName"		"ClassLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"classname"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"200"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
	}
	"ItemsLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ItemsLabel"
		"font"			"HudFontSmall"
		"labelText"		"classname"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"215"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor"		"117 107 94 255"
		"centerwrap"	"1"
	}
	
	"NoSteamLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NoSteamLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#NoSteamNoItems"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"250"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	"NoGCLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NoGCLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#NoGCNoItems"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"250"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	"SelectLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SelectLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#SelectClassLoadout"
		"textAlignment"	"north"
		"xpos"			"r0"
		"ypos"			"300"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "117 107 94 255"
	}
	"LoadoutChangesLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"LoadoutChangesLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#LoadoutChangesUpdate"
		"textAlignment"	"north"
		"xpos"			"r0"
		"ypos"			"35"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}
	
	"class_loadout_panel"
	{
		"ControlName"		"CClassLoadoutPanel"
		"fieldName"			"class_loadout_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"1"
		"visible"			"0"
	}
	"backpack_panel"
	{
		"ControlName"		"CBackpackPanel"
		"fieldName"			"backpack_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"1"
		"visible"			"0"
	}
	
	"InspectionPanel"
	{
		"fieldName"		"InspectionPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"400"
		"zpos"				"2"
		"visible"		"0"
		"proportionaltoparent"	"0"
		"bgcolor_override"	"30 25 25 0"
	}

	"ShowExplanationsButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ShowExplanationsButton"
		"xpos"			"r0"
		"ypos"			"10"
		"zpos"			"100"
		"wide"			"0"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"?"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"0"
		"Command"		"show_explanations"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"StartExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"StartExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"140"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-150"
		"end_y"			"190"
		"end_wide"		"300"
		"end_tall"		"155"
		"callout_inparents_x"	"c0"
		"callout_inparents_y"	"150"
		"next_explanation"		"BackpackExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#LoadoutExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"260"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#LoadoutExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"260"
			"tall"			"85"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"280"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"125"
			"zpos"			"-1"
			"wide"			"300"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"260"
			"ypos"			"125"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}		
	}	
	
	"BackpackExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"BackpackExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-320"
		"end_y"			"60"
		"end_wide"		"250"
		"end_tall"		"130"
		"callout_inparents_x"	"c-255"
		"callout_inparents_y"	"240"
		"next_explanation"		"CraftingExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#BackpackExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#BackpackExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"210"
			"tall"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"100"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"100"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"210"
			"ypos"			"100"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}		
	}	
	
	"CraftingExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"CraftingExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-210"
		"end_y"			"60"
		"end_wide"		"250"
		"end_tall"		"140"
		"callout_inparents_x"	"c-130"
		"callout_inparents_y"	"240"
		"next_explanation"		"ArmoryExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#CraftingExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#CraftingExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"210"
			"tall"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"110"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"210"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}	
	}	
	
	"ArmoryExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"ArmoryExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-120"
		"end_y"			"60"
		"end_wide"		"250"
		"end_tall"		"140"
		"callout_inparents_x"	"c0"
		"callout_inparents_y"	"240"
		"next_explanation"		"TradingExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#ArmoryExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#ArmoryExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"210"
			"tall"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"110"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"210"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}	
	}
	
	"TradingExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"TradingExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-30"
		"end_y"			"60"
		"end_wide"		"250"
		"end_tall"		"140"
		"callout_inparents_x"	"c130"
		"callout_inparents_y"	"240"
		"next_explanation"		"PatternsExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#TradingExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TradingExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"210"
			"tall"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"110"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"210"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}	
	}

	"PatternsExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"PatternsExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c130"
		"end_y"			"60"
		"end_wide"		"250"
		"end_tall"		"140"
		"callout_inparents_x"	"c255"
		"callout_inparents_y"	"240"
		"next_explanation"		"ExplanationExplanation"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#WeaponPatternsExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#WeaponPatternsExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"35"
			"wide"			"210"
			"tall"			"75"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"110"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
		"NextButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"NextButton"
			"xpos"			"210"
			"ypos"			"110"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"nextexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}				
		}	
	}
	
	"ExplanationExplanation"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"ExplanationExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c100"
		"end_y"			"100"
		"end_wide"		"250"
		"end_tall"		"120"
		"callout_inparents_x"	"c285"
		"callout_inparents_y"	"30"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#ExplanationExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#ExplanationExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"210"
			"tall"			"65"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
		"PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"PrevButton"
			"xpos"			"10"
			"ypos"			"90"
			"zpos"			"10"
			"wide"			"30"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"prevexplanation"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"235 226 202 255"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"30"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}				
		}		
		"PositionLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PositionLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%explanationnumber%"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"90"
			"zpos"			"-1"
			"wide"			"250"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "200 80 60 255"
		}
	}	
	
	"armory_panel"
	{
		"ControlName"		"CArmoryPanel"
		"fieldName"			"armory_panel"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f0"
		"tall"				"400"
		"zpos"				"500"
		"visible"			"0"
	}



}
